food_items_list = [
    "Apple",
    "Banana",
    "Orange",
    "Grapes",
    "Strawberries",
    "Blueberries",
    "Potato",
    "Carrot",
    "Lettuce",
    "Spinach",
    "Tomato",
    "Cucumber",
    "Onion",
    "Bell Pepper",
    "Broccoli",
    "Chicken",
    "Beef",
    "Pork",
    "Salmon",
    "Tuna",
    "Eggs",
    "Milk",
    "Cheese",
    "Yogurt",
    "Bread",
    "Rice",
    "Pasta",
    "Cereal",
    "Oatmeal",
    "Flour",
    "Sugar",
    "Salt",
    "Pepper",
    "Olive Oil",
    "Cooking Oil",
    "Butter",
    "Honey",
    "Peanut Butter",
    "Jam",
    "Ketchup",
    "Mustard",
    "Mayonnaise",
    "Soy Sauce",
    "Vinegar",
    "Salsa",
    "Chips",
    "Cookies",
    "Ice Cream",
    "Chocolate",
    "Coffee",
    "Tea",
    "Juice",
    "Water",
    "Soda",
    "Canned Soup",
    "Canned Vegetables",
    "Canned Fruits",
    "Granola Bars",
    "Frozen Vegetables",
    "Frozen Fruits",
    "Frozen Pizza",
    "Spaghetti Sauce",
    "Canned Beans",
    "Pancake Mix",
    "Maple Syrup",
    "Spices",
    "Nuts",
    "Dried Fruits",
    "Baking Powder",
    "Baking Soda",
    "Yeast",
    "Canned Tomatoes",
    "Bacon",
    "Ham",
    "Hot Dogs",
    "Ground Turkey",
    "Ground Chicken",
    "Avocado",
    "Pineapple",
    "Melon",
    "Peach",
    "Pear",
    "Plum",
    "Cabbage",
    "Zucchini",
    "Asparagus",
    "Artichoke",
    "Mushroom",
    "Cottage Cheese",
    "Sour Cream",
    "Cream Cheese",
    "Tofu",
    "Pita Bread",
    "Baguette",
    "Croissant",
    "Biscuits",
    "Bagels",
    "Tortillas",
    "Waffles",
    "Pancakes",
    "Popcorn",
    "Raisins",
    "Almonds",
    "Walnuts",
    "Cashews",
    "Pistachios",
    "Sunflower Seeds",
    "Quinoa",
    "Barley",
    "Couscous",
    "Lentils",
    "Black Beans",
    "Chickpeas",
    "Kidney Beans",
    "Miso",
    "Sushi Rice",
    "Whole Chicken",
    "Ground Beef",
    "Ground Pork",
    "Fish Fillets",
    "Shrimp",
    "Crab",
    "Lobster",
    "Clams",
    "Oysters",
    "Scallops",
    "Breadcrumbs",
    "Cornstarch",
    "Cornmeal",
    "Hamburger Buns",
    "Hot Dog Buns",
    "Lemon",
    "Lime",
    "Parsley",
    "Cilantro",
    "Basil",
    "Mint",
    "Rosemary",
    "Thyme",
    "Garlic",
    "Ginger",
    "Cinnamon",
    "Nutmeg",
    "Paprika",
    "Cumin",
    "Curry Powder",
    "Vanilla Extract",
    "Balsamic Vinegar",
    "White Vinegar",
    "Red Wine Vinegar",
    "Ranch Dressing",
    "Italian Dressing",
    "Balsamic Dressing",
    "Sesame Oil",
    "Hoisin Sauce",
    "Teriyaki Sauce",
    "Chocolate Syrup",
    "Marshmallows",
    "Hamburger Patties",
    "Hot Dog Sausages",
    "Hot Dog Buns",
    "Steak",
    "Ribeye",
    "Sirloin",
    "Brisket",
    "Ground Beef",
    "Ground Turkey",
    "Ground Chicken",
    "Pork Chops",
    "Pork Ribs",
    "Pork Tenderloin",
    "Lamb Chops",
    "Lamb Shoulder",
    "Lamb Leg",
    "Duck",
    "Turkey",
    "Salami",
    "Bologna",
    "Prosciutto",
    "Pastrami",
    "Pepperoni",
    "Cheddar",
    "Mozzarella",
    "Swiss",
    "Brie",
    "Feta",
    "Parmesan",
    "Goat Cheese",
    "Blue Cheese",
    "Gouda",
    "Havarti",
    "Cottage Cheese",
    "Sour Cream",
    "Cream Cheese",
    "Iceberg Lettuce",
    "Romaine Lettuce",
    "Arugula",
    "Kale",
    "Collard Greens",
    "Cabbage",
    "Brussels Sprouts",
    "Celery",
    "Radish",
    "Turnip",
    "Sweet Potato",
    "Pumpkin",
    "Butternut Squash",
    "Acorn Squash",
    "Eggplant",
    "Zucchini",
    "Bell Pepper",
    "Jalapeno",
    "Anaheim Pepper",
    "Poblano Pepper",
    "Serrano Pepper",
    "Cayenne Pepper",
    "Black Pepper",
    "White Pepper",
    "Cayenne Pepper",
    "Oregano",
    "Cajun Seasoning",
    "Onion Powder",
    "Garlic Powder",
    "Cumin",
    "Turmeric",
    "Paprika",
    "Bay Leaves",
    "Cinnamon",
    "Nutmeg",
    "Ginger",
    "Chili Powder",
    "Cardamom",
    "Allspice",
    "Sage",
    "Rosemary",
    "Thyme",
    "Fennel",
    "Coriander",
    "Dill",
    "Mustard Powder",
    "Cloves",
    "Cocoa Powder",
    "Baking Powder",
    "Baking Soda",
    "Yeast",
    "Vanilla Extract",
    "Brown Sugar",
    "Powdered Sugar",
    "Granulated Sugar",
    "Honey",
    "Maple Syrup",
    "Agave Syrup",
    "Corn Syrup",
    "Molasses",
    "Peanut Butter",
    "Almond Butter",
    "Cashew Butter",
    "Sunflower Butter",
    "Nutella",
    "Chocolate Spread",
    "Jam",
    "Jelly",
    "Marmalade",
    "Apple Sauce",
    "Salsa",
    "Guacamole",
    "Hummus",
    "Tzatziki",
    "Mayonnaise",
    "Ketchup",
    "Mustard",
    "Horseradish",
    "Worcestershire Sauce",
    "Soy Sauce",
    "Teriyaki Sauce",
    "Fish Sauce",
    "Hoison Sauce",
    "Oyster Sauce",
    "Rice Vinegar",
    "Balsamic Vinegar",
    "Apple Cider Vinegar",
    "Red Wine Vinegar",
    "White Wine Vinegar",
    "Lemon Juice",
    "Lime Juice",
    "Orange Juice",
    "Pineapple Juice",
    "Cranberry Juice",
    "Grape Juice",
    "Tomato Juice",
    "V8 Juice",
    "Coconut Water",
    "Club Soda",
    "Tonic Water",
    "Sparkling Water",
    "Still Water",
    "Cola",
    "Diet Cola",
    "Lemon-Lime Soda",
    "Root Beer",
    "Ginger Ale",
    "Orange Soda",
    "Cream Soda",
    "Fruit Punch",
    "Iced Tea",
    "Hot Tea",
    "Black Tea",
    "Green Tea",
    "Chamomile Tea",
    "Peppermint Tea",
    "Rooibos Tea",
    "Chai Tea",
    "Espresso",
    "Coffee",
    "Decaf Coffee",
    "Instant Coffee",
    "Coffee Pods",
    "French Press",
    "Drip Coffee",
    "Latte",
    "Cappuccino",
    "Mocha",
    "Macchiato",
    "Americano",
    "Flat White",
    "Cold Brew",
    "Iced Coffee",
    "Matcha Latte",
    "Green Smoothie",
    "Fruit Smoothie",
    "Protein Shake",
    "Chocolate Milk",
    "Soy Milk",
    "Almond Milk",
    "Oat Milk",
    "Cashew Milk",
    "Coconut Milk",
    "Hemp Milk",
    "Rice Milk",
    "Yogurt",
    "Greek Yogurt",
    "Frozen Yogurt",
    "Low-Fat Yogurt",
    "Whole Milk Yogurt",
    "Plant-Based Yogurt",
    "Cheddar Cheese",
    "Mozzarella Cheese",
    "Swiss Cheese",
    "Brie Cheese",
    "Parmesan Cheese",
    "Cream Cheese",
    "Feta Cheese",
    "Goat Cheese",
    "Blue Cheese",
    "Gouda Cheese",
    "Havarti Cheese",
    "Provolone Cheese",
    "Ricotta Cheese",
    "Cottage Cheese",
    "American Cheese",
    "Muenster Cheese",
    "Monterey Jack Cheese",
    "Colby Cheese",
    "Pepper Jack Cheese",
    "Gruyere Cheese",
    "Fontina Cheese",
    "Camembert Cheese",
    "Cheddar Cheese",
    "Brie Cheese",
    "Gouda Cheese",
    "Parmesan Cheese",
    "Cream Cheese",
    "Feta Cheese",
    "Goat Cheese",
    "Blue Cheese",
    "Ricotta Cheese",
    "Cottage Cheese",
    "Mozzarella Cheese",
    "Swiss Cheese",
    "Provolone Cheese",
    "Havarti Cheese",
    "Pepper Jack Cheese",
    "Gruyere Cheese",
    "Boursin Cheese",
    "Camembert Cheese",
    "Edam Cheese",
    "Chevre Cheese",
    "Mascarpone Cheese",
    "Roquefort Cheese",
    "Gorgonzola Cheese",
    "Tofu",
    "Tempeh",
    "Seitan",
    "Textured Vegetable Protein (TVP)",
    "Veggie Burger",
    "Veggie Sausage",
    "Veggie Hot Dog",
    "Veggie Meatballs",
    "Veggie Ground",
    "Plant-Based Meat Alternatives",
    "Gluten-Free Bread",
    "Whole Wheat Bread",
    "Multigrain Bread",
    "Sourdough Bread",
    "Rye Bread",
    "Pumpernickel Bread",
    "Baguette",
    "Ciabatta",
    "Focaccia",
    "Naan",
    "Pita Bread",
    "Tortillas",
    "Corn Tortillas",
    "Flour Tortillas",
    "Whole Wheat Tortillas",
    "Lavash",
    "Flatbread",
    "Crackers",
    "Saltine Crackers",
    "Ritz Crackers",
    "Wheat Thins",
    "Triscuits",
    "Club Crackers",
    "Pretzels",
    "Rice Cakes",
    "Popcorn",
    "Microwave Popcorn",
    "Kettle Corn",
    "Caramel Corn",
    "Chips",
    "Potato Chips",
    "Tortilla Chips",
    "Corn Chips",
    "Pita Chips",
    "Doritos",
    "Cheetos",
    "Fritos",
    "Lays",
    "Pringles",
    "Sun Chips",
    "Rice Krispies",
    "Corn Flakes",
    "Frosted Flakes",
    "Lucky Charms",
    "Cheerios",
    "Cocoa Puffs",
    "Froot Loops",
    "Raisin Bran",
    "Special K",
    "Granola",
    "Muesli",
    "Oatmeal",
    "Steel-Cut Oats",
    "Rolled Oats",
    "Instant Oats",
    "Quaker Oats",
    "Milk",
    "Whole Milk",
    "2% Milk",
    "1% Milk",
    "Skim Milk",
    "Almond Milk",
    "Soy Milk",
    "Coconut Milk",
    "Cashew Milk",
    "Oat Milk",
    "Rice Milk",
    "Lactose-Free Milk",
    "Chocolate Milk",
    "Butter",
    "Salted Butter",
    "Unsalted Butter",
    "Whipped Butter",
    "Flavored Butter",
    "Margarine",
    "Ghee",
    "Eggs",
    "Large Eggs",
    "Extra-Large Eggs",
    "Jumbo Eggs",
    "Brown Eggs",
    "Cage-Free Eggs",
    "Organic Eggs",
    "Free-Range Eggs",
    "Pasteurized Eggs",
    "Egg Whites",
    "Egg Yolks",
    "Egg Substitute",
    "Egg Replacer",
    "Egg Beaters",
    "Quail Eggs",
    "Duck Eggs",
    "Goose Eggs",
    "Turkey Eggs",
    "Emu Eggs",
    "Ostrich Eggs",
    "Fish",
    "Salmon",
    "Tuna",
    "Trout",
    "Cod",
    "Haddock",
    "Sardines",
    "Anchovies",
    "Herring",
    "Mackerel",
    "Halibut",
    "Mahi-Mahi",
    "Swordfish",
    "Barramundi",
    "Snapper",
    "Grouper",
    "Tilefish",
    "Flounder",
    "Perch",
    "Pollock",
    "Catfish",
    "Carp",
    "Basa",
    "Arctic Char",
    "Caviar",
    "Roe",
    "Fish Fillets",
    "Fish Steaks",
    "Shellfish",
    "Shrimp",
    "Prawns",
    "Lobster",
    "Crab",
    "Clams",
    "Mussels",
    "Oysters",
    "Scallops",
    "Crawfish",
    "Squid",
    "Octopus",
    "Cuttlefish",
    "Seafood",
    "Calamari",
    "Sea Cucumber",
    "Sea Urchin",
    "Sea Asparagus",
    "Sea Grapes",
    "Sea Lettuce",
    "Sea Sponge",
    "Seaweed",
    "Wakame",
    "Nori",
    "Kombu",
    "Dulse",
    "Hijiki",
    "Arame",
    "Agar",
    "Fish Sauce",
    "Soy Sauce",
    "Oyster Sauce",
    "Hoisin Sauce",
    "Teriyaki Sauce",
    "Ponzu Sauce",
    "Sweet Chili Sauce",
    "Black Bean Sauce",
    "Plum Sauce",
    "Tartar Sauce",
    "Cocktail Sauce",
    "Hot Sauce",
    "Sriracha",
    "Tabasco Sauce",
    "Frank's RedHot",
    "Cholula",
    "Valentina",
    "Texas Pete",
    "Louisiana Hot Sauce",
    "Crystal Hot Sauce",
    "Trappey's Hot Sauce",
    "El Yucateco Hot Sauce",
    "Tapatio Hot Sauce",
    "Piri-Piri Sauce",
    "Peri-Peri Sauce",
    "Harissa",
    "Sambal",
    "Pepper Sauce",
    "Tomato Sauce",
    "Spaghetti Sauce",
    "Marinara Sauce",
    "Alfredo Sauce",
    "Pesto Sauce",
    "Carbonara Sauce",
    "Vodka Sauce",
    "Bolognese Sauce",
    "Arrabbiata Sauce",
    "Puttanesca Sauce",
    "Cream Sauce",
    "Cheese Sauce",
    "Barbecue Sauce",
    "Hickory Smoke Sauce",
    "Kansas City BBQ Sauce",
    "Texas BBQ Sauce",
    "Carolina BBQ Sauce",
    "Memphis BBQ Sauce",
    "Mustard BBQ Sauce",
    "White BBQ Sauce",
    "Buffalo Sauce",
    "Honey Mustard Sauce",
    "Dijon Mustard",
    "Yellow Mustard",
    "Whole Grain Mustard",
    "Spicy Brown Mustard",
    "English Mustard",
    "Delhi Mustard",
    "Coarse-Grain Mustard",
    "Horseradish Mustard",
    "Honey Dijon Mustard",
    "Sweet Mustard",
    "Hot Mustard",
    "Worcestershire Sauce",
    "Tonkatsu Sauce",
    "Honey Garlic Sauce",
    "Mushroom Sauce",
    "Sesame Sauce",
    "Chimichurri Sauce",
    "Tahini Sauce",
    "Hummus",
    "Baba Ganoush",
    "Salsa",
    "Pico de Gallo",
    "Guacamole",
    "Chutney",
    "Relish",
    "Tzatziki",
    "Raita",
    "Harissa",
    "Sriracha",
    "Chili Paste",
    "Wasabi",
    "Soybean Paste",
    "Black Bean Paste",
    "Miso Paste",
    "Tomato Paste",
    "Peanut Sauce",
    "Peanut Butter",
    "Almond Butter",
    "Cashew Butter",
    "Hazelnut Butter",
    "Walnut Butter",
    "Pecan Butter",
    "Macadamia Nut Butter",
    "Sunflower Seed Butter",
    "Chocolate Spread",
    "Marshmallow Fluff",
    "Nutella",
    "Fruit Preserves",
    "Fruit Jam",
    "Fruit Jelly",
    "Fruit Marmalade",
    "Fruit Compote",
    "Fruit Curd",
    "Apple Sauce",
    "Cranberry Sauce",
    "Orange Marmalade",
    "Lemon Curd",
    "Strawberry Jam",
    "Raspberry Jam",
    "Blueberry Jam",
    "Blackberry Jam",
    "Apricot Jam",
    "Peach Jam",
    "Grape Jam",
    "Mixed Berry Jam",
    "Cherry Jam",
    "Pineapple Jam",
    "Fig Jam",
    "Plum Jam",
    "Quince Jam",
    "Kiwi Jam",
    "Mango Jam",
    "Papaya Jam",
    "Passion Fruit Jam",
    "Guava Jam",
    "Dragon Fruit Jam",
    "Coconut Jam",
    "Lychee Jam",
    "Rambutan Jam",
    "Durian Jam",
    "Watermelon Jam",
    "Avocado Jam",
    "Green Bean Jam",
    "Salsa",
    "Tomato Salsa",
    "Pineapple Salsa",
    "Mango Salsa",
    "Peach Salsa",
    "Black Bean Salsa",
    "Corn Salsa",
    "Avocado Salsa",
    "Cucumber Salsa",
    "Strawberry Salsa",
    "Blueberry Salsa",
    "Raspberry Salsa",
    "Pomegranate Salsa",
    "Kiwi Salsa",
    "Watermelon Salsa",
    "Guava Salsa",
    "Papaya Salsa",
    "Cranberry Salsa",
    "Tomatillo Salsa",
    "Chipotle Salsa",
    "Habanero Salsa",
    "Jalapeno Salsa",
    "Serrano Salsa",
    "Scotch Bonnet Salsa",
    "Ghost Pepper Salsa",
    "Carolina Reaper Salsa",
    "Hot Salsa",
    "Mild Salsa",
    "Sweet Salsa",
    "Savory Salsa",
    "Fruit Salsa",
    "Vegetable Salsa",
    "Herb Salsa",
    "Spicy Salsa",
    "Zesty Salsa",
    "Chunky Salsa",
    "Smooth Salsa",
    "Thick Salsa",
    "Thin Salsa",
    "Creamy Salsa",
    "Tangy Salsa",
    "Fresh Salsa",
    "Homemade Salsa",
    "Store-Bought Salsa",
    "Gourmet Salsa",
    "Traditional Salsa",
    "Modern Salsa",
    "Exotic Salsa",
    "Worldly Salsa",
    "Ethnic Salsa",
    "International Salsa",
    "Global Salsa",
    "Local Salsa",
    "Seasonal Salsa",
    "Organic Salsa",
    "Natural Salsa",
    "Healthy Salsa",
    "GMO-Free Salsa",
    "Gluten-Free Salsa",
    "Vegan Salsa",
    "Vegetarian Salsa",
    "Paleo Salsa",
    "Keto Salsa",
    "Low-Fat Salsa",
    "Low-Sodium Salsa",
    "Low-Sugar Salsa",
    "Low-Calorie Salsa",
    "Low-Carb Salsa",
    "Sugar-Free Salsa",
    "Non-GMO Salsa",
    "Preservative-Free Salsa",
    "Fat-Free Salsa",
    "Dairy-Free Salsa",
    "All-Natural Salsa",
    "Spices",
    "Salt",
    "Pepper",
    "Cumin",
    "Paprika",
    "Chili Powder",
    "Cayenne Pepper",
    "Turmeric",
    "Ginger",
    "Cinnamon",
    "Nutmeg",
    "Allspice",
    "Cloves",
    "Cardamom",
    "Coriander",
    "Fennel Seeds",
    "Mustard Seeds",
    "Celery Seeds",
    "Poppy Seeds",
    "Sesame Seeds",
    "Caraway Seeds",
    "Dill Seeds",
    "Anise Seeds",
    "Chia Seeds",
    "Flax Seeds",
    "Fenugreek Seeds",
    "Ajwain Seeds",
    "Sumac",
    "Za'atar",
    "Herbs",
    "Basil",
    "Rosemary",
    "Thyme",
    "Oregano",
    "Parsley",
    "Sage",
    "Dill",
    "Cilantro",
    "Mint",
    "Chives",
    "Tarragon",
    "Marjoram",
    "Bay Leaves",
    "Lavender",
    "Lemongrass",
    "Coriander",
    "Chervil",
    "Fenugreek",
    "Lemon Balm",
    "Lovage",
    "Sorrel",
    "Chamomile",
    "Savory",
    "Epazote",
    "Borage",
    "Cress",
    "Saffron",
    "Kaffir Lime Leaves",
    "Curry Leaves",
    "Lemon Verbena",
    "Nasturtium",
    "Watercress",
    "Spice Blends",
    "Italian Seasoning",
    "Herbes de Provence",
    "Pumpkin Spice",
    "Garam Masala",
    "Curry Powder",
    "Chinese Five Spice",
    "Za'atar",
    "Ras El Hanout",
    "Adobo",
    "Berbere",
    "Taco Seasoning",
    "Cajun Seasoning",
    "Old Bay Seasoning",
    "Creole Seasoning",
    "Chili Seasoning",
    "Fajita Seasoning",
    "Tandoori Masala",
    "Poultry Seasoning",
    "Steak Seasoning",
    "Seafood Seasoning",
    "Chai Masala",
    "BBQ Rub",
    "Sazon",
    "Harissa",
    "Dukkah",
    "Furikake",
    "Fines Herbes",
    "Chartreuse",
    "Salmagundi",
    "Salmis",
    "Persillade",
    "Gordita",
    "Frumenty",
    "Frumentaceous",
    "Comestible",
    "Aliment",
    "Sustenance",
    "Nutrition",
    "Regimen",
    "Provisions",
    "Eatables",
    "Groceries",
    "Consumables",
    "Slops",
    "Gruel",
    "Larder",
    "Lard",
    "Victuals",
    "Dough",
    "Stuff",
    "Meat",
    "Vegetables",
    "Fruits",
    "Bread",
    "Rice",
    "Pasta",
    "Fish",
    "Eggs",
    "Cheese",
    "Yogurt",
    "Milk",
    "Nuts",
    "Seeds",
    "Cereals"
    ]
